services:
    db2:
      image: blacklabelops/hsqldb
      hostname: trinity-db-ml
      extra_hosts:
        - "trinity-db-ml:${TRINITY_DB_IP}"
      container_name: trinity-db-ml
      environment:
        HSQLDB_DATABASE_HOST: trinity-db-ml
        HSQLDB_USER: sa
        HSQLDB_PASSWORD: 
        HSQLDB_TRACE: "false"
        HSQLDB_SILENT: "true"
        HSQLDB_REMOTE: "false"
        HSQLDB_DATABASE_ALIAS: "test"
      ports:
        - "7901:9001"
      volumes:
        - "./data-ml:/opt/database"
#      restart: always
    web2:
      image: tomcat:9.0.97
      hostname: trinity-web-ml
      extra_hosts:
        - "trinity-db-ml:${TRINITY_DB_IP}"
      container_name: trinity-web-ml
      environment:
        JDBC_URL: jdbc:hsqldb:hsql://trinity-db-ml:7901/test
        JDBC_USER: sa
        JDBC_PASS: 
      ports:
        - "7880:8080"
        - "7843:8443"
        - "7809:8009"
      volumes:
        - ./trinity-en:/usr/local/tomcat/webapps/trinity
        - ./config-ml/trinity-docker.key:/usr/local/tomcat/conf/trinity-docker.key
        - ./config-ml/server.xml:/usr/local/tomcat/conf/server.xml
        - ./config-ml/context.xml:/usr/local/tomcat/conf/context.xml
        - ./lib/hsqldb.jar:/usr/local/tomcat/lib/hsqldb.jar
        - ./lib/mariadb-java-client-2.7.2.jar:/usr/local/tomcat/lib/mariadb-java-client-2.7.2.jar
        - ./lib/ojdbc14.jar:/usr/local/tomcat/lib/ojdbc14.jar
        - ./logs-ml:/usr/local/tomcat/logs
      links:
        - db2
#      restart: always  
