<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.io.File"%>
<%@ page import="java.util.Iterator"%>
<%@ page import="java.util.*"%>

<%@ page import="com.stuko.anaconda.XmlConfig.*"%>
<%@ page import="com.stuko.anaconda.Exception.ExceptionCenter"%>
<%@ page import="com.stuko.anaconda.front.*"%>
<%@ page import="com.stuko.anaconda.Auth.*"%>
<%@ page import="com.stuko.anaconda.value.*"%>
<%@ page import="com.stuko.anaconda.business.*"%>
<%@ page import="com.stuko.anaconda.openapi.*"%>
<%@ page import="com.stuko.anaconda.util.*"%>


 <section class="page-section" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">우리(소셜 프로젝트)는?</h2>
          <h3 class="section-subheading text-muted">저희(소셜 프로젝트)들은 세상을 좀 더 여유롭고 행복하게 변화시키기 위해 노력하고 있습니다</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <ul class="timeline">
            <li>
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="/bt/agency/img/about/1.jpg" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4>2018 ~ </h4>
                  <h4 class="subheading">DUNA(free) 오픈, TRINITY 3.1 오픈 및 새로운 서비스/아이디어 준비중</h4>
                </div>
                <div class="timeline-body">
                  <p class="text-muted">긴시간의 소프트웨어로봇 개발 운영 시스템의 준비과정을 거쳐 보다 많은 사람들이 소프트웨어로봇을 쉽게 사용할 수 있도록 무료 서비스(서버가 버틸수 있는데 까지)를 오픈하였으며 현재도 계속 새로운 아이디어를 통해 신규 서비스를 준비중에 있습니다.</p>
                  <p class="text-muted">저희 베스트멤버는 TRINITY 라는 웹 브라우저기반의 "개발과 유지보수" 솔루션을 개발하여, 원격/재택 환경으로 쉽고 편하게 솔루션과 서비스를 개발하고 있습니다..</p>
                </div>
              </div>
            </li>
            <li class="timeline-inverted">
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="/bt/agency/img/about/4.jpg" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4>2017-2018</h4>
                  <h4 class="subheading">소프트웨어로봇 시스템 개발</h4>
                </div>
                <div class="timeline-body">
                  <p class="text-muted">저희는 다양한 분야에 쉽게 적용될 수 있는 유용한 소프트웨어로봇 개발 운영 시스템을 개발해 왔습니다.</p>
                </div>
              </div>
            </li>
            <li>
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="/bt/agency/img/about/3.jpg" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4>2012-2016</h4>
                  <h4 class="subheading">실시간 분석 엔진</h4>
                </div>
                <div class="timeline-body">
                  <p class="text-muted">WAYD(What Are You Doing?)라고 불리는 작은 프로젝트를 통해 실시간 분석 엔진을 개발해 왔으며 현재는 DUNA 소프트웨어로봇 시스템으로 성장하여 다양한 분야에 활용이 가능한 유용한 엔진으로 자리 잡고 있습니다</p>
                </div>
              </div>
            </li>
          
            <li class="timeline-inverted">
              <div class="timeline-image">
                <h4>베스트멤버<br>새로운 시작<br>새로운 세상</h4>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
